`ndarray[start:end]`

`ndarray[start:]`

`ndarray[:end]`

In [1]:
import numpy as np 

x = np.arange(10)
print(x)


[0 1 2 3 4 5 6 7 8 9]


In [2]:
print(x[2:6]) #start from index 2 to index 6 exclusive 

[2 3 4 5]


In [3]:
x = np.arange(10).reshape(5,2)
print(x)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


get access 2nd row 

In [8]:
print(x[2, :])

[4 5]


get access all the rows of 2nd columns 

In [11]:
print(x[:, 1])

[1 3 5 7 9]


To get access a single element use ```ndarrady[row,column]``` formate

In [24]:
print(x[3,0])

6
