`ndarray[start:end]`

`ndarray[start:]`

`ndarray[:end]`

In [57]:
import numpy as np 

x = np.arange(10)
print(x)


[0 1 2 3 4 5 6 7 8 9]


In [58]:
print(x[2:6]) #start from index 2 to index 6 exclusive 

[2 3 4 5]


In [67]:
x = np.arange(10).reshape(5,2)
print(x)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


get access 2nd row 

In [68]:
print(x[2, :])

[4 5]


get access all the values of 2nd columns, this way return a **rank 1 ndarray**

In [69]:
#x = np.arange(25).reshape(5,5)
print(x)
print()

# rank 1 ndarray 
r1 = x[:, 1]
print(r1)
print(r1.shape)
print()

# rank 2 ndarray 
r2 = x[:, 1:2]
print(r2)
print(r2.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

[1 3 5 7 9]
(5,)

[[1]
 [3]
 [5]
 [7]
 [9]]
(5, 1)


In [0]:
print(x[:, 1])

To get access a single element use ```ndarrady[row,column]``` formate

In [0]:
print(x[3,0])

In [0]:
y = np.arange(25, dtype=int).reshape(5,5)
print(y)
print(y.dtype)

In [0]:
# get only the values of 4th columns and mean 
print(y[:, 3])
print(y[:,3].mean())


Get the **average** value of each column and row

In [0]:
print(y.mean(axis=0)) # mean of all the columns
print(y.mean(axis=1)) # mean of all the rows 