`ndarray[start:end]`

`ndarray[start:]`

`ndarray[:end]`

In [3]:
import numpy as np 

x = np.arange(10)
print(x)


[0 1 2 3 4 5 6 7 8 9]


In [4]:
print(x[2:6]) #start from index 2 to index 6 exclusive 

[2 3 4 5]


In [5]:
x = np.arange(10).reshape(5,2)
print(x)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


get access 2nd row 

In [6]:
print(x[2, :])

[4 5]


get access all the values of 2nd columns 

In [7]:
print(x[:, 1])

[1 3 5 7 9]


To get access a single element use ```ndarrady[row,column]``` formate

In [8]:
print(x[3,0])

6


In [24]:
y = np.arange(25, dtype=int).reshape(5,5)
print(y)
print(y.dtype)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
int32


In [25]:
# get only the values of 4th columns and mean 
print(y[:, 3])
print(y[:,3].mean())


[ 3  8 13 18 23]
13.0


Get the **average** value of each column and row

In [26]:
print(y.mean(axis=0)) # mean of all the columns
print(y.mean(axis=1)) # mean of all the rows 

[10. 11. 12. 13. 14.]
[ 2.  7. 12. 17. 22.]
