In [2]:
import numpy as np

## zeros((row, column))

In [5]:
x = np.zeros((3,2), dtype=int)
print(x)

[[0 0]
 [0 0]
 [0 0]]


In [6]:
print(x.dtype)

int32


## ones((row, column))

In [7]:
x = np.ones((3,2))
print(x)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


## Identity matrix 
np.eye(n)

In [8]:
x = np.eye(4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## arange(start, end, step)
if no end or step arugment is specified then first arugment will be end parameter and step will be 1. Though `arange` be used to floating point value but better solution is `linespace`

In [11]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


## linespace(start, end, step)

In [24]:
x = np.linspace(4, 10.5, 25, endpoint=False)
print(x)

[ 4.    4.26  4.52  4.78  5.04  5.3   5.56  5.82  6.08  6.34  6.6   6.86
  7.12  7.38  7.64  7.9   8.16  8.42  8.68  8.94  9.2   9.46  9.72  9.98
 10.24]


## reshape(ndarray, (row, column))

In [28]:
x = np.arange(20)
x = np.reshape(x, (4,5))
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [29]:
x = np.arange(25).reshape(5,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


## random.random(row, column)
return a matrix with random value between 0 and 1 

In [31]:
x = np.random.random((3,3))
print(x)

[[0.66981473 0.74109022 0.45229111]
 [0.64483418 0.1882408  0.84617848]
 [0.24369212 0.70892801 0.78584928]]


## random.randint(start, end, (row, column))
return a matrix with random integer value 