In [2]:
import numpy as np

## np.zeros((row, column))

In [5]:
x = np.zeros((3,2), dtype=int)
print(x)

[[0 0]
 [0 0]
 [0 0]]


In [6]:
print(x.dtype)

int32


## np.ones((row, column))

In [7]:
x = np.ones((3,2))
print(x)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


## Identity matrix 
np.eye(n)

In [8]:
x = np.eye(4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## np.arange(start, end, step)
if no end or step arugment is specified then first arugment will be end parameter and step will be 1

In [11]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]
